export type UIPatternCategory = 'smc' | 'volatility' | 'classical' | 'candlestick' | 'sequence';

export type BackendPatternCategory = 'candlestick' | 'classical' | 'continuation' | 'reversal' | 'breakout' | 'structure' | 'volatility' | 'gap' | 'liquidity';

export interface PatternRegistryEntry {
  name: string;
  category: UIPatternCategory;
  backendCategory: BackendPatternCategory;
  color: string;
  icon: string;
  description: string;
  contributesToConfluence: boolean;
  showOnChart: boolean;
}

export const UI_CATEGORY_ORDER: UIPatternCategory[] = ['smc', 'volatility', 'classical', 'candlestick', 'sequence'];

export const UI_CATEGORY_LABELS: Record<UIPatternCategory, string> = {
  smc: 'Smart Money Concepts',
  volatility: 'Volatility & Momentum',
  classical: 'Classical Patterns',
  candlestick: 'Candlestick Patterns',
  sequence: 'Sequences',
};

export const UI_CATEGORY_COLORS: Record<UIPatternCategory, string> = {
  smc: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
  volatility: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
  classical: 'bg-teal-500/20 text-teal-400 border-teal-500/30',
  candlestick: 'bg-violet-500/20 text-violet-400 border-violet-500/30',
  sequence: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30',
};

export const PATTERN_REGISTRY: Record<string, PatternRegistryEntry> = {
  'Bullish Order Block': {
    name: 'Bullish Order Block',
    category: 'smc',
    backendCategory: 'structure',
    color: '#22c55e',
    icon: 'BoxSelect',
    description: 'Institutional buying zone where price is likely to bounce',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bearish Order Block': {
    name: 'Bearish Order Block',
    category: 'smc',
    backendCategory: 'structure',
    color: '#ef4444',
    icon: 'BoxSelect',
    description: 'Institutional selling zone where price is likely to reject',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bullish Breaker Block': {
    name: 'Bullish Breaker Block',
    category: 'smc',
    backendCategory: 'structure',
    color: '#4ade80',
    icon: 'Shield',
    description: 'Failed bearish order block now acting as bullish support',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bearish Breaker Block': {
    name: 'Bearish Breaker Block',
    category: 'smc',
    backendCategory: 'structure',
    color: '#f87171',
    icon: 'Shield',
    description: 'Failed bullish order block now acting as bearish resistance',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Liquidity Sweep High': {
    name: 'Liquidity Sweep High',
    category: 'smc',
    backendCategory: 'liquidity',
    color: '#ef4444',
    icon: 'ArrowUpFromLine',
    description: 'Price swept above a high to grab liquidity before reversing',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Liquidity Sweep Low': {
    name: 'Liquidity Sweep Low',
    category: 'smc',
    backendCategory: 'liquidity',
    color: '#22c55e',
    icon: 'ArrowDownFromLine',
    description: 'Price swept below a low to grab liquidity before reversing',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bullish Liquidity Grab': {
    name: 'Bullish Liquidity Grab',
    category: 'smc',
    backendCategory: 'liquidity',
    color: '#22c55e',
    icon: 'Magnet',
    description: 'Smart money grabbed sell-side liquidity for a bullish move',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bearish Liquidity Grab': {
    name: 'Bearish Liquidity Grab',
    category: 'smc',
    backendCategory: 'liquidity',
    color: '#ef4444',
    icon: 'Magnet',
    description: 'Smart money grabbed buy-side liquidity for a bearish move',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bullish Breakout Failure Reversal': {
    name: 'Bullish Breakout Failure Reversal',
    category: 'smc',
    backendCategory: 'reversal',
    color: '#22c55e',
    icon: 'RotateCcw',
    description: 'Failed bearish breakout leading to bullish reversal',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bearish Breakout Failure Reversal': {
    name: 'Bearish Breakout Failure Reversal',
    category: 'smc',
    backendCategory: 'reversal',
    color: '#ef4444',
    icon: 'RotateCw',
    description: 'Failed bullish breakout leading to bearish reversal',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bullish CHOCH': {
    name: 'Bullish CHOCH',
    category: 'smc',
    backendCategory: 'structure',
    color: '#22c55e',
    icon: 'TrendingUp',
    description: 'Change of character from bearish to bullish structure',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bearish CHOCH': {
    name: 'Bearish CHOCH',
    category: 'smc',
    backendCategory: 'structure',
    color: '#ef4444',
    icon: 'TrendingDown',
    description: 'Change of character from bullish to bearish structure',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bullish BOS': {
    name: 'Bullish BOS',
    category: 'smc',
    backendCategory: 'breakout',
    color: '#22c55e',
    icon: 'ArrowUpRight',
    description: 'Break of structure confirming bullish continuation',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bearish BOS': {
    name: 'Bearish BOS',
    category: 'smc',
    backendCategory: 'breakout',
    color: '#ef4444',
    icon: 'ArrowDownRight',
    description: 'Break of structure confirming bearish continuation',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bearish Swing Failure Pattern': {
    name: 'Bearish Swing Failure Pattern',
    category: 'smc',
    backendCategory: 'reversal',
    color: '#ef4444',
    icon: 'ArrowDown',
    description: 'Failed swing high signaling bearish reversal',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bullish Swing Failure Pattern': {
    name: 'Bullish Swing Failure Pattern',
    category: 'smc',
    backendCategory: 'reversal',
    color: '#22c55e',
    icon: 'ArrowUp',
    description: 'Failed swing low signaling bullish reversal',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Higher High / Higher Low': {
    name: 'Higher High / Higher Low',
    category: 'smc',
    backendCategory: 'structure',
    color: '#22c55e',
    icon: 'TrendingUp',
    description: 'Bullish market structure with ascending pivots',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Lower High / Lower Low': {
    name: 'Lower High / Lower Low',
    category: 'smc',
    backendCategory: 'structure',
    color: '#ef4444',
    icon: 'TrendingDown',
    description: 'Bearish market structure with descending pivots',
    contributesToConfluence: true,
    showOnChart: true,
  },

  'Volatility Squeeze': {
    name: 'Volatility Squeeze',
    category: 'volatility',
    backendCategory: 'volatility',
    color: '#f59e0b',
    icon: 'Minimize2',
    description: 'Bollinger Bands inside Keltner Channel indicating imminent expansion',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'NR7': {
    name: 'NR7',
    category: 'volatility',
    backendCategory: 'volatility',
    color: '#f59e0b',
    icon: 'Shrink',
    description: 'Narrowest range of last 7 bars signaling breakout potential',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bullish Volume Climax': {
    name: 'Bullish Volume Climax',
    category: 'volatility',
    backendCategory: 'volatility',
    color: '#22c55e',
    icon: 'BarChart3',
    description: 'Extreme volume spike on bullish candle signaling capitulation or momentum',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish Volume Climax': {
    name: 'Bearish Volume Climax',
    category: 'volatility',
    backendCategory: 'volatility',
    color: '#ef4444',
    icon: 'BarChart3',
    description: 'Extreme volume spike on bearish candle signaling capitulation or momentum',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bullish EMA Compression Snap': {
    name: 'Bullish EMA Compression Snap',
    category: 'volatility',
    backendCategory: 'volatility',
    color: '#22c55e',
    icon: 'Zap',
    description: 'EMAs compressed then snapped bullish with expanding momentum',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish EMA Compression Snap': {
    name: 'Bearish EMA Compression Snap',
    category: 'volatility',
    backendCategory: 'volatility',
    color: '#ef4444',
    icon: 'Zap',
    description: 'EMAs compressed then snapped bearish with expanding momentum',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bullish VWAP Reversal': {
    name: 'Bullish VWAP Reversal',
    category: 'volatility',
    backendCategory: 'reversal',
    color: '#22c55e',
    icon: 'RefreshCcw',
    description: 'Price reclaimed VWAP from below with strong bullish momentum',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish VWAP Reversal': {
    name: 'Bearish VWAP Reversal',
    category: 'volatility',
    backendCategory: 'reversal',
    color: '#ef4444',
    icon: 'RefreshCw',
    description: 'Price rejected from VWAP with strong bearish momentum',
    contributesToConfluence: true,
    showOnChart: false,
  },

  'Rising Wedge': {
    name: 'Rising Wedge',
    category: 'classical',
    backendCategory: 'classical',
    color: '#f43f5e',
    icon: 'Triangle',
    description: 'Bearish reversal pattern with converging upward trendlines',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Falling Wedge': {
    name: 'Falling Wedge',
    category: 'classical',
    backendCategory: 'classical',
    color: '#10b981',
    icon: 'Triangle',
    description: 'Bullish reversal pattern with converging downward trendlines',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Ascending Triangle': {
    name: 'Ascending Triangle',
    category: 'classical',
    backendCategory: 'classical',
    color: '#10b981',
    icon: 'Triangle',
    description: 'Bullish continuation with flat resistance and rising support',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Descending Triangle': {
    name: 'Descending Triangle',
    category: 'classical',
    backendCategory: 'classical',
    color: '#f43f5e',
    icon: 'Triangle',
    description: 'Bearish continuation with flat support and falling resistance',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Symmetrical Triangle': {
    name: 'Symmetrical Triangle',
    category: 'classical',
    backendCategory: 'classical',
    color: '#a78bfa',
    icon: 'Triangle',
    description: 'Neutral consolidation with converging support and resistance',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bull Flag': {
    name: 'Bull Flag',
    category: 'classical',
    backendCategory: 'continuation',
    color: '#10b981',
    icon: 'Flag',
    description: 'Bullish continuation with sharp rally followed by parallel pullback',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bear Flag': {
    name: 'Bear Flag',
    category: 'classical',
    backendCategory: 'continuation',
    color: '#f43f5e',
    icon: 'Flag',
    description: 'Bearish continuation with sharp decline followed by parallel pullback',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bull Pennant': {
    name: 'Bull Pennant',
    category: 'classical',
    backendCategory: 'continuation',
    color: '#10b981',
    icon: 'Bookmark',
    description: 'Bullish continuation with converging trendlines after a rally',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Bear Pennant': {
    name: 'Bear Pennant',
    category: 'classical',
    backendCategory: 'continuation',
    color: '#f43f5e',
    icon: 'Bookmark',
    description: 'Bearish continuation with converging trendlines after a decline',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Horizontal Channel': {
    name: 'Horizontal Channel',
    category: 'classical',
    backendCategory: 'classical',
    color: '#a78bfa',
    icon: 'Minus',
    description: 'Price oscillating between horizontal support and resistance',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Channel Up': {
    name: 'Channel Up',
    category: 'classical',
    backendCategory: 'classical',
    color: '#10b981',
    icon: 'TrendingUp',
    description: 'Price trending within parallel ascending support and resistance',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Channel Down': {
    name: 'Channel Down',
    category: 'classical',
    backendCategory: 'classical',
    color: '#f43f5e',
    icon: 'TrendingDown',
    description: 'Price trending within parallel descending support and resistance',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Broadening Formation': {
    name: 'Broadening Formation',
    category: 'classical',
    backendCategory: 'classical',
    color: '#a78bfa',
    icon: 'Maximize2',
    description: 'Expanding volatility with diverging trendlines',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Rounded Bottom': {
    name: 'Rounded Bottom',
    category: 'classical',
    backendCategory: 'reversal',
    color: '#10b981',
    icon: 'CircleDot',
    description: 'Gradual bullish reversal forming a U-shaped bottom',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Rounded Top': {
    name: 'Rounded Top',
    category: 'classical',
    backendCategory: 'reversal',
    color: '#f43f5e',
    icon: 'CircleDot',
    description: 'Gradual bearish reversal forming an inverted U-shaped top',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Double Top': {
    name: 'Double Top',
    category: 'classical',
    backendCategory: 'reversal',
    color: '#f43f5e',
    icon: 'ChevronsUp',
    description: 'Bearish reversal with two peaks at similar price levels',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Double Bottom': {
    name: 'Double Bottom',
    category: 'classical',
    backendCategory: 'reversal',
    color: '#10b981',
    icon: 'ChevronsDown',
    description: 'Bullish reversal with two troughs at similar price levels',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Triple Top': {
    name: 'Triple Top',
    category: 'classical',
    backendCategory: 'reversal',
    color: '#f43f5e',
    icon: 'ChevronsUp',
    description: 'Bearish reversal with three peaks at similar price levels',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Triple Bottom': {
    name: 'Triple Bottom',
    category: 'classical',
    backendCategory: 'reversal',
    color: '#10b981',
    icon: 'ChevronsDown',
    description: 'Bullish reversal with three troughs at similar price levels',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Head & Shoulders': {
    name: 'Head & Shoulders',
    category: 'classical',
    backendCategory: 'reversal',
    color: '#f43f5e',
    icon: 'Crown',
    description: 'Bearish reversal with a higher peak between two lower peaks',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Inverse Head & Shoulders': {
    name: 'Inverse Head & Shoulders',
    category: 'classical',
    backendCategory: 'reversal',
    color: '#10b981',
    icon: 'Crown',
    description: 'Bullish reversal with a lower trough between two higher troughs',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Cup and Handle': {
    name: 'Cup and Handle',
    category: 'classical',
    backendCategory: 'continuation',
    color: '#10b981',
    icon: 'Coffee',
    description: 'Bullish continuation with rounded bottom and small pullback handle',
    contributesToConfluence: true,
    showOnChart: true,
  },

  'Hammer': {
    name: 'Hammer',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'ArrowUp',
    description: 'Bullish reversal with long lower wick after a decline',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Inverted Hammer': {
    name: 'Inverted Hammer',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'ArrowUp',
    description: 'Bullish reversal with long upper wick after a decline',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Hanging Man': {
    name: 'Hanging Man',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'ArrowDown',
    description: 'Bearish reversal with long lower shadow at top of uptrend',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Shooting Star': {
    name: 'Shooting Star',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'Star',
    description: 'Bearish reversal with long upper wick at top of uptrend',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Doji': {
    name: 'Doji',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#a78bfa',
    icon: 'Crosshair',
    description: 'Indecision candle with open and close at nearly same level',
    contributesToConfluence: false,
    showOnChart: false,
  },
  'Spinning Top': {
    name: 'Spinning Top',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#a78bfa',
    icon: 'RotateCw',
    description: 'Indecision candle with small body and long wicks on both sides',
    contributesToConfluence: false,
    showOnChart: false,
  },
  'Bullish Engulfing': {
    name: 'Bullish Engulfing',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'Maximize',
    description: 'Bullish candle fully engulfs prior bearish candle',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish Engulfing': {
    name: 'Bearish Engulfing',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'Maximize',
    description: 'Bearish candle fully engulfs prior bullish candle',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bullish Harami': {
    name: 'Bullish Harami',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'Minimize',
    description: 'Small bullish candle contained within prior bearish candle body',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish Harami': {
    name: 'Bearish Harami',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'Minimize',
    description: 'Small bearish candle contained within prior bullish candle body',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Inside Bar': {
    name: 'Inside Bar',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#a78bfa',
    icon: 'AlignCenter',
    description: 'Current bar range fully inside prior bar range',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Outside Bar': {
    name: 'Outside Bar',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#a78bfa',
    icon: 'Expand',
    description: 'Current bar range fully engulfs prior bar range',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Morning Star': {
    name: 'Morning Star',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'Sunrise',
    description: 'Three-candle bullish reversal with gap-down doji and bullish close',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Evening Star': {
    name: 'Evening Star',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'Sunset',
    description: 'Three-candle bearish reversal with gap-up doji and bearish close',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Marubozu': {
    name: 'Marubozu',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#a78bfa',
    icon: 'Square',
    description: 'Strong momentum candle with no or minimal wicks',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bullish Marubozu': {
    name: 'Bullish Marubozu',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'Square',
    description: 'Strong bullish candle with no lower wick showing buying dominance',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish Marubozu': {
    name: 'Bearish Marubozu',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'Square',
    description: 'Strong bearish candle with no upper wick showing selling dominance',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Three White Soldiers': {
    name: 'Three White Soldiers',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'ChevronUp',
    description: 'Three consecutive strong bullish candles signaling reversal',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Three Black Crows': {
    name: 'Three Black Crows',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'ChevronDown',
    description: 'Three consecutive strong bearish candles signaling reversal',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Piercing Pattern': {
    name: 'Piercing Pattern',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'ArrowUpRight',
    description: 'Bullish reversal where second candle opens below and closes above midpoint',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Dark Cloud Cover': {
    name: 'Dark Cloud Cover',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'Cloud',
    description: 'Bearish reversal where second candle opens above and closes below midpoint',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Tweezers': {
    name: 'Tweezers',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#a78bfa',
    icon: 'GripVertical',
    description: 'Two candles with matching highs or lows signaling reversal',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bullish Belt Hold': {
    name: 'Bullish Belt Hold',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'ArrowUp',
    description: 'Opens at low and drives upward with strong body',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish Belt Hold': {
    name: 'Bearish Belt Hold',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'ArrowDown',
    description: 'Opens at high and sells off with strong body',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Three Inside Up': {
    name: 'Three Inside Up',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'ChevronUp',
    description: 'Small bullish candle inside prior bearish, confirmed by bullish close',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Three Inside Down': {
    name: 'Three Inside Down',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'ChevronDown',
    description: 'Small bearish candle inside prior bullish, confirmed by bearish close',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Three Outside Up': {
    name: 'Three Outside Up',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'ChevronsUp',
    description: 'Bullish engulfing followed by further bullish confirmation',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Three Outside Down': {
    name: 'Three Outside Down',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'ChevronsDown',
    description: 'Bearish engulfing followed by further bearish confirmation',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bullish Kicker': {
    name: 'Bullish Kicker',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'Zap',
    description: 'Sharp gap up from prior bearish candle with strong bullish follow-through',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish Kicker': {
    name: 'Bearish Kicker',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'Zap',
    description: 'Sharp gap down from prior bullish candle with strong bearish follow-through',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bullish Abandoned Baby': {
    name: 'Bullish Abandoned Baby',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#22c55e',
    icon: 'Baby',
    description: 'Gap-down doji isolated between bearish and bullish candles',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Bearish Abandoned Baby': {
    name: 'Bearish Abandoned Baby',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#ef4444',
    icon: 'Baby',
    description: 'Gap-up doji isolated between bullish and bearish candles',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Tri-Star Doji': {
    name: 'Tri-Star Doji',
    category: 'candlestick',
    backendCategory: 'candlestick',
    color: '#a78bfa',
    icon: 'Stars',
    description: 'Three consecutive doji candles signaling major reversal',
    contributesToConfluence: true,
    showOnChart: false,
  },
  'Gap Up': {
    name: 'Gap Up',
    category: 'candlestick',
    backendCategory: 'gap',
    color: '#22c55e',
    icon: 'ArrowUpFromLine',
    description: 'Price opened above prior candle high creating a bullish gap',
    contributesToConfluence: false,
    showOnChart: true,
  },
  'Gap Down': {
    name: 'Gap Down',
    category: 'candlestick',
    backendCategory: 'gap',
    color: '#ef4444',
    icon: 'ArrowDownFromLine',
    description: 'Price opened below prior candle low creating a bearish gap',
    contributesToConfluence: false,
    showOnChart: true,
  },

  'Sweep → Displacement → BOS': {
    name: 'Sweep → Displacement → BOS',
    category: 'sequence',
    backendCategory: 'structure',
    color: '#06b6d4',
    icon: 'Workflow',
    description: 'Liquidity sweep followed by displacement candle and break of structure',
    contributesToConfluence: true,
    showOnChart: true,
  },
  'Compression → Breakout': {
    name: 'Compression → Breakout',
    category: 'sequence',
    backendCategory: 'breakout',
    color: '#06b6d4',
    icon: 'Rocket',
    description: 'Tight price compression followed by directional breakout',
    contributesToConfluence: true,
    showOnChart: true,
  },
};

const lowerCaseMap = new Map<string, PatternRegistryEntry>();
for (const entry of Object.values(PATTERN_REGISTRY)) {
  lowerCaseMap.set(entry.name.toLowerCase(), entry);
}

export function getPatternEntry(name: string): PatternRegistryEntry | undefined {
  return PATTERN_REGISTRY[name] ?? lowerCaseMap.get(name.toLowerCase());
}

export function getPatternsByUICategory(category: UIPatternCategory): PatternRegistryEntry[] {
  return Object.values(PATTERN_REGISTRY).filter(entry => entry.category === category);
}
