import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { AlertTriangle } from "lucide-react";
import { useAuth } from "@clerk/clerk-react";
import { useToast } from "@/hooks/use-toast";

const STRIPE_CHECKOUT_URL = "https://buy.stripe.com/14AdRb95S3c99Oe2Hzew801";

interface TermsAcceptanceModalProps {
  open: boolean;
  onClose: () => void;
}

export default function TermsAcceptanceModal({ open, onClose }: TermsAcceptanceModalProps) {
  const [agreed, setAgreed] = useState(false);
  const [loading, setLoading] = useState(false);
  const { userId } = useAuth();
  const { toast } = useToast();

  const handleContinue = async () => {
    if (!agreed) return;
    setLoading(true);

    try {
      const res = await fetch("/api/log-terms-acceptance", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId: userId || "anonymous" }),
      });

      if (!res.ok) {
        throw new Error("Failed to log acceptance");
      }

      window.open(STRIPE_CHECKOUT_URL, "_blank", "noopener,noreferrer");
      onClose();
    } catch {
      toast({
        title: "Something went wrong",
        description: "Could not process your acceptance. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
      setAgreed(false);
    }
  };

  const handleClose = () => {
    setAgreed(false);
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) handleClose(); }}>
      <DialogContent className="max-w-lg" data-testid="modal-terms-acceptance">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-lg" data-testid="text-terms-title">
            <AlertTriangle className="w-5 h-5 text-amber-400" />
            Before You Start Your Free Trial
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-2 text-sm text-muted-foreground leading-relaxed max-h-[60vh] overflow-y-auto">
          <p>
            <strong className="text-foreground/80">Risk Warning:</strong> Options trading involves substantial risk of loss and is not suitable for all investors. The value of options can fluctuate significantly, and you may lose more than your initial investment. Past performance is not indicative of future results.
          </p>
          <p>
            <strong className="text-foreground/80">No Guarantee of Accuracy:</strong> The signals, analytics, grades, and recommendations provided by this application are generated by automated algorithms and may not always be accurate, complete, or timely. Market conditions change rapidly, and no system can predict market movements with certainty.
          </p>
          <p>
            <strong className="text-foreground/80">Not Financial Advice:</strong> Nothing on this platform constitutes financial, investment, legal, or tax advice. All content is for informational and educational purposes only. You should consult with a qualified financial advisor before making any investment decisions. Trading Terminal and its creators are not registered investment advisors, broker-dealers, or financial planners.
          </p>
          <p>
            <strong className="text-foreground/80">Limitation of Liability:</strong> Trading Terminal shall not be held liable for any losses, damages, or claims arising from the use of this application or reliance on any information provided herein. By using this platform, you acknowledge that all trading decisions are made at your own risk.
          </p>
          <p>
            <strong className="text-foreground/80">Subscription Terms:</strong> Your free trial lasts 2 days. You may cancel at any time before the trial period ends and you will not be charged. After the trial, your subscription will automatically renew at $25 per week unless cancelled.
          </p>
        </div>

        <div className="flex items-start gap-3 p-3 rounded-md bg-muted/50 border border-border/50">
          <Checkbox
            id="terms-agree"
            checked={agreed}
            onCheckedChange={(v) => setAgreed(v === true)}
            data-testid="checkbox-terms-agree"
          />
          <label htmlFor="terms-agree" className="text-sm cursor-pointer leading-relaxed select-none">
            I agree to the Terms of Service, Privacy Policy, and Risk Disclosures.
          </label>
        </div>

        <DialogFooter className="gap-2 sm:gap-0">
          <Button variant="ghost" onClick={handleClose} data-testid="button-terms-cancel">
            Cancel
          </Button>
          <Button
            disabled={!agreed || loading}
            onClick={handleContinue}
            className="bg-gradient-to-r from-cyan-500 to-blue-500 text-white border-0"
            data-testid="button-terms-continue"
          >
            {loading ? "Processing..." : "Continue"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
